<?php include_once('partials/header.php'); ?>
    <div class="container">
    	<div class="row">
    		<h3 class="text-center">About</h3>
    		<div class="col-md-10 col-md-offset-1">
				<p class="lead">We have developed an online database (<a href="http://www.prm-db.org">http://www.prm-db.org</a>) that provides access to the new data reported here, and also, to previous phage-derived data for PDZ, SH3 and WW domains (<a target="_blank" href="https://pubmed.ncbi.nlm.nih.gov/28890361/">Teyra et al, 2017</a>; <a target="_blank" href="https://pubmed.ncbi.nlm.nih.gov/18828675/">Tonikian et al, 2008</a>; <a target="_blank" href="https://pubmed.ncbi.nlm.nih.gov/23549480/">Xin et al, 2013</a>). In total, the online database contains 7,984 unique peptide ligands, each validated to bind one of 500 PRMs representing 82 structural families. The database can be queried by protein or family name and the search can be restricted by species. For each PRM, the database provides the specificity logo, the top three phage-derived peptide ligands, and the best-matched PRM-ligand structure in the PDB. Users can also download the full list of peptide ligands, the PWM matrices containing the amino acid frequencies, and a list of the best-matched PRM-ligand structures in the PDB. Moreover, the database provides a list of human proteins matching PRM binding motifs, which was generated by scanning the human proteome with the PWMs. Combined with other experimental data, these can help to prioritize biological experiments to explore putative natural interactions (Jain & Bader, 2016). Thus, the compiled and searchable database should facilitate many structural, functional and biological studies of PRMs and SLiMs.
				</p>

				<!-- <p class="lead">If the phage-derived peptide information contained in this website becomes useful for your research,
				please cite: Large-scale survey and database of high affinity ligands for peptide recognition modules (Under Review; 2019)  </p> -->
				<br>
	        </div>
      	</div>
    </div>
    <?php include_once('partials/footer.php'); ?>
	</body>
</html>